name: login-mega-manual


on:
  [workflow_dispatch]


concurrency:
  group: login-and-schedule
  cancel-in-progress: false


jobs:
  call-workflow:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - name: Get folder name from current workflow name
            run: |
              read -ra Arr <<< ${{ github.workflow }}
              folder=${Arr[1]}
              echo "folder name is $folder"
              echo "Calling autolog workflow now"
              
          - name: Call autolog workflow
            uses: schmwong/keep-accounts-active/.github/workflows/reusable/autolog.yml@first-reusable-workflow
            with:
              folder: $folder
              platform-name: Mega
              secrets: inherit
              
