name: reusable-autolog

on:
  workflow_call:
  
    secrets:
      WORKFLOW_TOKEN:
        required: true
      USR_MEGA_1:
        required: false
      PWD_MEGA_1:
        required: false
      USR_MEGA_2:
        required: false
      PWD_MEGA_2:
        required: false
      USR_ONEDRIVE_1:
        required: false
      PWD_ONEDRIVE_1:
        required: false
      USR_ONEDRIVE_2:
        required: false
      PWD_ONEDRIVE_2:
        required: false
      USR_YAHOO_1:
        required: false
      PWD_YAHOO_1:
        required: false
        
  
    # inputs in this case are arguments passed from caller workflow
    inputs:
    
      # name of folder to commit csv logfile to
      folder:
        required: true
        type: string
        
      # account platform name to be reflected in commit message, e.g. OneDrive
      platform-name:
        default: ${{ inputs.folder }}
        type: string
        
    
  
# Workflow level env variables:
# Declare GitHub Personal Access Token 
# and login credentials of each account here

env:
    WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
    USR_MEGA_1: ${{ secrets.USR_MEGA_1 }}
    PWD_MEGA_1: ${{ secrets.PWD_MEGA_1 }}
    USR_MEGA_2: ${{ secrets.USR_MEGA_2 }}
    PWD_MEGA_2: ${{ secrets.PWD_MEGA_2 }}
    USR_ONEDRIVE_1: ${{ secrets.USR_ONEDRIVE_1 }}
    PWD_ONEDRIVE_1: ${{ secrets.PWD_ONEDRIVE_1 }}
    USR_ONEDRIVE_2: ${{ secrets.USR_ONEDRIVE_2 }}
    PWD_ONEDRIVE_2: ${{ secrets.PWD_ONEDRIVE_2 }}
    USR_YAHOO_1: ${{ secrets.USR_YAHOO_1 }}
    PWD_YAHOO_1: ${{ secrets.PWD_YAHOO_1 }}
    
    

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repo content
          uses: actions/checkout@v3       # checkout repo content of caller workflow to github runner.

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
              python-version: 3.9.6

        - name: Setup dependencies
          run: |
            pip install python-dotenv
            pip install playwright
            playwright install firefox
            pip install pandas

        - name: Clone private repo folder
          run: |
            git clone \
            --depth 1 \
            --filter=blob:none \
            --sparse \
            https://schmwong:${{ env.WORKFLOW_TOKEN }}@github.com/schmwong/login-log \
            ;
            cd login-log
            git sparse-checkout init --cone
            git sparse-checkout set ${{ inputs.folder }}
            cd ..

        - name: Run Python script
          run: python keep-${{ inputs.folder }}-active.py 

        - name: Commit and push folder to private repo if updated
          run: |
            cd login-log
            datestamp=$(date -u +%F)
            git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git add ./${{ inputs.folder }}
            if ! git diff-index --quiet HEAD; then
              git commit -m "updated ${{ inputs.platform-name }} logs for ${datestamp} (manual)" -- ./${{ inputs.folder }} 
              git push "https://${GITHUB_ACTOR}:${{ env.WORKFLOW_TOKEN }}@github.com/schmwong/login-log.git" \
              HEAD:main || exit 0
            fi
